import React from 'react';

const AddAProduct = () => {
    console.log("here")
    return (
        <div>
            <h1>Add A Product</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi magnam aliquid laudantium rem ea. Necessitatibus voluptatum quia soluta hic rerum nisi deleniti! Mollitia qui, alias accusamus ab sed dignissimos itaque, vitae quam quasi doloribus consectetur? Maxime minima velit similique doloremque sequi numquam, expedita dolor ullam suscipit quidem. Debitis facere modi mollitia fuga quod, neque exercitationem facilis iste id ratione quibusdam autem, vitae ipsam nam, praesentium ex doloribus perferendis laudantium beatae est. Voluptatibus eveniet laborum necessitatibus totam. Culpa nulla cum debitis magnam provident saepe voluptates quis. Perspiciatis et voluptate minima voluptas velit libero sapiente voluptatibus sunt eveniet pariatur, quasi inventore iure. Animi quam magnam modi. Aspernatur ut suscipit repellat. Numquam officia deleniti atque. Neque ea, reprehenderit vitae iste sint voluptates obcaecati tempore provident blanditiis omnis porro mollitia itaque dolores perspiciatis illum, dignissimos totam dolor ab esse debitis. Repellat vero ut, ratione totam rerum hic. Culpa fuga repellendus ea a, animi molestiae quibusdam, ipsum eaque amet quos, consectetur necessitatibus dolor quam illum sequi perferendis possimus corrupti vitae iusto omnis! Culpa quasi esse quisquam molestiae quam quos aliquam necessitatibus fuga officiis. Cum accusamus nisi esse possimus amet animi commodi vitae minus numquam voluptatum aperiam quibusdam ea, quia dicta, saepe harum nihil velit earum impedit qui ullam officia voluptatibus? Blanditiis, consectetur eligendi aliquam tempora dolore necessitatibus possimus minus dolor accusamus cum nihil fugiat consequuntur dolores, quod quis magnam in. Debitis neque voluptatem, expedita earum adipisci voluptatibus mollitia dolorum, quas tempora quibusdam aliquid nulla non sunt, consequatur quae facere eos. Rem unde nemo laboriosam maxime deleniti iusto, earum accusamus aperiam voluptate maiores labore reiciendis illo rerum quidem quas ducimus molestiae esse autem soluta possimus ut! Repudiandae, labore numquam. Quasi eum accusantium cum reprehenderit fugiat nostrum quae. Error, eligendi rem. Necessitatibus deleniti labore libero, id repellendus maiores odio ea debitis! Impedit nam minus incidunt dolor voluptas.</p>
        </div>
    );
};

export default AddAProduct;